NataliaAlvarezIspc/proyecto-ispc-ecommerce

back-end/model/articulo.py
Completar modelo Artículo. Merge contra back-end-logic. Closes #85
=> completar modelo de articulo

.github/workflows/python.yml, back-end/coverage.ini, back-end/model/administrador.py, back-end/model/agenda.py, back-end/model/carrito.py, back-end/model/cliente.py, back-end/model/content_provider/base_memoria.py, back-end/model/database.py, back-end/model/deposito.py, back-end/model/envio.py, back-end/model/libro_diario.py, back-end/model/seleccion.py, back-end/model/usuario.py, back-end/model/venta.py, back-end/requirements.txt, back-end/tests/administrador_tests.py, back-end/tests/articulo_tests.py, back-end/tests/cliente_tests.py, back-end/tests/seleccion_tests.py, back-end/tests/usuario_tests.py, back-end/tests/venta_tests.py
Crear pipeline en Github para que ejecute las pruebas automáticamente al subir código
=> Crear pipeline

front-end/enbalde/src/app/shared/footer/footer.component.html
En el link CATÁLOGO del footer faltaba hacer el routing a la pagina Catálogo. Aquí está solucionado.
=> Solucionando el routing del catálogo del footer

front-end/enbalde/src/app/pages/carrito/carrito/carrito.component.css, front-end/enbalde/src/app/pages/carrito/carrito/carrito.component.html, front-end/enbalde/src/app/pages/carrito/carrito/carrito.component.ts, front-end/enbalde/src/app/pages/catalogo/catalogo.component.css, front-end/enbalde/src/app/pages/catalogo/catalogo.component.html, front-end/enbalde/src/app/pages/catalogo/catalogo.component.ts
Rama creada para refactorizar Catálogo y Carrito
=> Refactor cat car

documentacion/heladeria_13.04.2023.sql
Agregar nombre e imagen (1 sola) a artículo
=> Actualización de script base de datos

front-end/enbalde/src/app/pages/abm-envios/abm-envios.component.html, front-end/enbalde/src/app/pages/abm-envios/abm-envios.component.ts, front-end/enbalde/src/app/pages/abm-envios/modelo/modelo.envio.ts, front-end/enbalde/src/app/pages/carrito/carrito/carrito.component.html, front-end/enbalde/src/app/pages/carrito/carrito/carrito.component.ts, front-end/enbalde/src/app/pages/producto/producto.component.html, front-end/enbalde/src/app/pages/producto/producto.component.ts
Agregado menu de envio y unos cambios visuales para las tarjetas de producto
=> Menu envio

front-end/enbalde/src/app/pages/carrito/carrito/carrito.component.html, front-end/enbalde/src/app/pages/home/home.component.css, front-end/enbalde/src/app/pages/home/home.component.html
Dimension nueva para cards en home, bugs en carrito solucionado
=> [UPDATE] Solucion de bugs en carrito, y estilo en home.

front-end/enbalde/src/app/app.component.spec.ts, front-end/enbalde/src/app/pages/alta-producto/alta-producto.component.spec.ts, front-end/enbalde/src/app/pages/carrito/carrito.component.spec.ts, front-end/enbalde/src/app/pages/catalogo/catalogo.component.spec.ts, front-end/enbalde/src/app/pages/contacto/contacto.component.spec.ts, front-end/enbalde/src/app/pages/login/login.component.spec.ts, front-end/enbalde/src/app/pages/login/login.component.ts, front-end/enbalde/src/app/pages/registracion/registracion.component.spec.ts, front-end/enbalde/src/app/pages/restablecer/restablecer.component.spec.ts, front-end/enbalde/src/app/shared/footer/footer.component.spec.ts, front-end/enbalde/src/app/shared/header/header.component.spec.ts, front-end/enbalde/src/app/shared/header/header.component.ts
Arreglo de tests de Angular (ng test).
=> Fix unit tests

front-end/enbalde/src/app/pages/catalogo/catalogo.component.ts, front-end/enbalde/src/app/productos.service.spec.ts, front-end/enbalde/src/app/productos.service.ts
=> agregar servicio de productos

front-end/enbalde/src/app/carrito.service.spec.ts, front-end/enbalde/src/app/carrito.service.ts, front-end/enbalde/src/app/pages/carrito/carrito.component.ts
Tengo entendido que esta vale por las 3 issues de servicio de carrito. Hice todo junto.
=> [ADD] Servicio de carrito

front-end/enbalde/src/app/pages/login/login.component.ts, front-end/enbalde/src/app/pages/registracion/registracion.component.html, front-end/enbalde/src/app/pages/registracion/registracion.component.ts, front-end/enbalde/src/app/pages/restablecer/restablecer.component.html, front-end/enbalde/src/app/pages/restablecer/restablecer.component.ts, front-end/enbalde/src/app/usuarios.service.ts
completando métodos en servicio usuarios, corrigiendo errores en html, inyectando servicios en components.ts correspondientes (login, registración, restablecer).
=> Crear clase servicios login en front

front-end/enbalde/src/app/pages/tipo-producto/tipo-producto.component.ts, front-end/enbalde/src/app/productos.service.ts
Servicio dentro de Productos para simplificar, no puede existir un tipo de producto sin producto.
=> 267 crear servicios para tipo productos

front-end/enbalde/src/app/app-routing.module.ts, front-end/enbalde/src/app/pages/abm-envios/abm-envios.component.html, front-end/enbalde/src/app/pages/abm-envios/abm-envios.component.ts, front-end/enbalde/src/app/pages/abm-envios/modelo/modelo.envio.ts, front-end/enbalde/src/app/pages/contacto/contacto.component.html, front-end/enbalde/src/app/pages/contacto/contacto.component.ts, front-end/enbalde/src/app/pages/item-envio/item-envio.component.html, front-end/enbalde/src/app/pages/item-envio/item-envio.component.spec.ts, front-end/enbalde/src/app/pages/item-envio/item-envio.component.ts, front-end/enbalde/src/app/pages/login/login.component.ts, front-end/enbalde/src/app/pages/pages.module.ts, front-end/enbalde/src/app/usuarios.service.ts
Modificaciones varias, primera versión de la edición de envíos.
=> Navigation

front-end/enbalde/src/app/pages/item-tipo-producto/item-tipo-producto.component.html, front-end/enbalde/src/app/pages/item-tipo-producto/item-tipo-producto.component.spec.ts, front-end/enbalde/src/app/pages/item-tipo-producto/item-tipo-producto.component.ts, front-end/enbalde/src/app/pages/pages.module.ts, front-end/enbalde/src/app/pages/producto/modelo/modelo.tipoProducto.ts, front-end/enbalde/src/app/pages/tipo-producto/tipo-producto.component.html, front-end/enbalde/src/app/pages/tipo-producto/tipo-producto.component.ts
Agregar editor de tipo de producto
=> Abm tipo producto

front-end/enbalde/src/app/pages/carrito/carrito.component.css, front-end/enbalde/src/app/pages/carrito/carrito.component.html, front-end/enbalde/src/app/pages/carrito/carrito.component.ts
Se agregó boton para seleccionar formas de pago. Tal cual como se muestra en la Img de referencia.
Opcion efectivo y mercado pago.
=> [ADD] Boton Seleccionar pago

front-end/enbalde/src/app/pages/catalogo/catalogo.component.css, front-end/enbalde/src/app/pages/catalogo/catalogo.component.html
=> [ADD] Bug solucionado en catálogo

back-end/django/.gitignore
Cambiar de enbalde/settings.py a server/settings.py
=> ajustar settings en gitignore

front-end/enbalde/src/app/app.module.ts, front-end/enbalde/src/app/home.service.spec.ts, front-end/enbalde/src/app/home.service.ts, front-end/enbalde/src/app/pages/home/home.component.css, front-end/enbalde/src/app/pages/home/home.component.html, front-end/enbalde/src/app/pages/home/home.component.ts
Consumo de API externa con Stylo incorporado.
=> Api externa

front-end/enbalde/src/app/app.module.ts, front-end/enbalde/src/app/carrito.service.ts, front-end/enbalde/src/app/compras.service.ts, front-end/enbalde/src/app/envios.service.ts, front-end/enbalde/src/app/ofertas.service.ts, front-end/enbalde/src/app/pages/abm-envios/abm-envios.component.ts, front-end/enbalde/src/app/pages/carrito/carrito.component.ts, front-end/enbalde/src/app/pages/carrito/modelo/modelo.seleccion.ts, front-end/enbalde/src/app/pages/catalogo/catalogo.component.ts, front-end/enbalde/src/app/pages/compras/compras.component.html, front-end/enbalde/src/app/pages/compras/compras.component.ts, front-end/enbalde/src/app/pages/compras/modelo/modelo.compra.ts, front-end/enbalde/src/app/pages/dashboard/dashboard.component.ts, front-end/enbalde/src/app/pages/ofertas/ofertas.component.ts, front-end/enbalde/src/app/pages/tipo-producto/tipo-producto.component.ts, front-end/enbalde/src/app/pages/ventas/modelo/modelo.venta.ts, front-end/enbalde/src/app/pages/ventas/ventas.component.html, front-end/enbalde/src/app/pages/ventas/ventas.component.ts, front-end/enbalde/src/app/productos.service.ts, front-end/enbalde/src/app/ventas.service.ts, front-end/enbalde/src/assets/carrito.json, front-end/enbalde/src/assets/compras.json, front-end/enbalde/src/assets/envios.json, front-end/enbalde/src/assets/ofertas.json, front-end/enbalde/src/assets/productos.json, front-end/enbalde/src/assets/tipoProductos.json, front-end/enbalde/src/assets/ventas.json
Hacer que los servicios levanten datos de un json para cada uno
=> Services json

front-end/enbalde/src/app/pages/carrito/carrito.component.html
Cambio de tipe checkbox a radio.
=> [REFACTOR] Boton actualizado

front-end/enbalde/src/app/pages/carrito/carrito.component.html
=> [UPDATE] Bug solucionado de carrito - Stylo nuevo a h2

back-end/django/server/settings.py, front-end/enbalde/src/app/shared/footer/footer.component.html
=> [ADD] Boton responsive todas las resoluciones

front-end/enbalde/src/app/pages/registracion/registracion.component.html
=> agregar dos puntos en etiqueta

front-end/enbalde/src/app/pages/producto/producto.component.html
=> agregar texto a propiedad alt de imagen

front-end/enbalde/src/app/pages/perfil/perfil.component.ts
=> inicializar usuario y perfilForm en constructor

front-end/enbalde/src/app/pages/tipo-producto/tipo-producto.component.html
=> ocultar columnas y mostrar mensaje cuando no hay tipos

front-end/enbalde/src/app/pages/ofertas/ofertas.component.html
=> borrar tabla y mostrar mensaje cuando no hay ofertas

front-end/enbalde/src/app/shared/footer/footer.component.html
Era lo que decia @rpgrca , quité solamente eso y se fue el error.
=> [ADD] Solucion bug a boton

front-end/enbalde/src/app/pages/login/login.component.css
=> quitar mayusculas del boton login

front-end/enbalde/src/app/pages/home/home.component.html
Se agregó la descripcion ALT a las img de "QUE HAY DE NUEVO" y tambien del carousel.
=> Arreglar alt de qué hay de nuevo

front-end/enbalde/src/app/pages/catalogo/catalogo.component.html, front-end/enbalde/src/app/pages/catalogo/catalogo.component.ts
=> [ADD] Solucion a bug - error de sintaxis

front-end/enbalde/src/app/pages/catalogo/catalogo.component.css, front-end/enbalde/src/app/pages/catalogo/catalogo.component.ts
Cree una función para que cuando se esa en un dispositivo menor a 780 de ancho no le permita acceder a la animacion de "zoom" pero, de esta misma función surgió un bug, el cual es el que si probas el responsive con la app de inspector esta sigue funcionando(osea que se rompe todo porque estas accediendo de una forma por asi decirlo forzada), por ende tambien le realicé el responsive en caso de que surja ese bug.
=> Click en catalogo en sm

front-end/enbalde/src/app/pages/contacto/contacto.component.ts, front-end/enbalde/src/app/pages/perfil/perfil.component.ts
Bug de enrutamiento solucionado de Perfil y también de Contacto, ahora funcionan correctamente.
=> No se rutea correctamente a la pag

front-end/enbalde/src/app/pages/login/login.component.html, front-end/enbalde/src/app/pages/login/login.component.ts, front-end/enbalde/src/app/pages/registracion/registracion.component.html
agregadas etiquetas a login
corrección de inconsistencias en registración
redireccionamiento a home en login
=> 412 tk152 agregar etiquetas al login

front-end/enbalde/src/app/pages/registracion/registracion.component.ts
acepta:
natalia@gmail.com
Natalia@gmail.com
Natalia1@gmail.com
natalia@Gmail.com
natalia@gmail.Com
Natalia@GMAIL.COM
natalia_@gmail.co
natalia-1@gmail.co
natalia-1@gmail-1.co
natalia@11g.com
natalia@1.com
natalia.a@gmail.com
natalia@gmail.c.com
natalia@gmail.1.com
natalia@1g.com
natalia@gmail.c
natalia-@gmail.co
natalia@gmail-.co
No acepta:
natalia,a@gmail.com
natalia;a@gmail.com
natalia@gmail,1.com
natalia@gmail;1.com
natalia@gmail;c.com
natalia@gmail,c.com
natalia,@gmail.com
natalia;@gmail.com
natalia@gmail.com.
natalia@gmail.com@
@natalia@gmail.com
aaa@a.com (por la restricción de más de 10 caracteres)
=> Patterns mail

front-end/enbalde/src/app/pages/carrito/carrito.component.css, front-end/enbalde/src/app/pages/carrito/carrito.component.html, front-end/enbalde/src/app/pages/home/home.component.css, front-end/enbalde/src/app/pages/home/home.component.html, front-end/enbalde/src/index.html
Animaciones simples del tipo FadeIN - agregadas solamente en Home(En partes que no molesten a la vista y que no quede sobre cargado). También en carrito (solamente en el titulo AÑADIR MAS PRODUCTOS, que eventualmente va ser un boton).
=> Animaciones

back-end/django/server/urls.py, front-end/enbalde/src/app/pages/item-producto/item-producto.component.ts, front-end/enbalde/src/app/services/imagenes.service.ts, front-end/enbalde/src/app/services/productos.service.ts, front-end/enbalde/src/environment/environment.prod.ts, front-end/enbalde/src/environment/environment.ts
Todas las API de Django van a empezar con /api/, por ejemplo, /api/articulos y /api/tipo_articulos
=> Api url change

.github/workflows/python.yml, back-end/django/enbalde/models.py, back-end/django/enbalde/serializers.py, back-end/django/enbalde/urls.py, back-end/django/enbalde/views/articulo_views.py, back-end/django/enbalde/views/common.py, back-end/django/enbalde/views/tipo_articulo_views.py, back-end/django/enbalde/views/usuario_views.py, back-end/django/server/urls.py, front-end/enbalde/src/app/pages/registracion/registracion.component.html, front-end/enbalde/src/app/pages/registracion/registracion.component.ts, front-end/enbalde/src/app/services/usuarios.service.ts
Pantalla de registración con back-end funcionando, puede crear nuevos usuarios
=> 67 tk13 back en python de pantalla de registracion

back-end/django/enbalde/views/usuario_views.py, back-end/django/server/settings.py, front-end/enbalde/src/app/app.module.ts, front-end/enbalde/src/app/models/modelo.usuario.ts, front-end/enbalde/src/app/pages/login/login.component.ts, front-end/enbalde/src/app/services/auth.interceptor.ts, front-end/enbalde/src/app/services/auth.service.spec.ts, front-end/enbalde/src/app/services/auth.service.ts, front-end/enbalde/src/app/services/usuarios.service.ts, front-end/enbalde/src/app/shared/header/header.component.html, front-end/enbalde/src/app/shared/header/header.component.ts
Se puede loguear y desloguear (se redirige al home cuando lo hace). Los links del encabezado aparecen y desaparecen dependiendo si esta logueado, y con qué tipo de usuario entró.
=> Conexion login

front-end/enbalde/src/app/app-routing.module.ts, front-end/enbalde/src/app/pages/item-usuario/item-usuario.component.html, front-end/enbalde/src/app/pages/item-usuario/item-usuario.component.spec.ts, front-end/enbalde/src/app/pages/item-usuario/item-usuario.component.ts, front-end/enbalde/src/app/pages/pages.module.ts, front-end/enbalde/src/app/pages/usuarios/usuarios.component.html, front-end/enbalde/src/app/pages/usuarios/usuarios.component.spec.ts, front-end/enbalde/src/app/pages/usuarios/usuarios.component.ts, front-end/enbalde/src/app/services/usuarios.service.ts, front-end/enbalde/src/app/shared/header/header.component.html
=> 482 tk160 listado de usuarios para administrador

front-end/enbalde/src/app/app-routing.module.ts, front-end/enbalde/src/app/models/modelo.usuario.ts, front-end/enbalde/src/app/services/auth.guard.spec.ts, front-end/enbalde/src/app/services/auth.guard.ts, front-end/enbalde/src/app/services/auth.service.ts
=> 402 feature agregar rutas protegidas

front-end/enbalde/src/app/pages/dashboard/dashboard.component.ts
=> refrescar productos despues de crear

front-end/enbalde/src/app/pages/catalogo/catalogo.component.html, front-end/enbalde/src/app/pages/catalogo/catalogo.component.ts
=> ocultar boton para agregar en carrito si no esta logueado

back-end/django/enbalde/serializers.py, back-end/django/enbalde/urls.py, front-end/enbalde/src/app/models/modelo.producto.ts, front-end/enbalde/src/app/pages/item-producto/item-producto.component.html, front-end/enbalde/src/app/pages/item-producto/item-producto.component.ts, front-end/enbalde/src/app/pages/item-tipo-producto/item-tipo-producto.component.ts, front-end/enbalde/src/app/services/imagenes.service.ts, front-end/enbalde/src/app/services/productos.service.ts
Usar el ViewSet para articulo en lugar de manejarlo a mano con APIView por el video del profesor
=> Articulo view

front-end/enbalde/src/app/app-routing.module.ts, front-end/enbalde/src/app/pages/carrito/carrito.component.html, front-end/enbalde/src/app/pages/carrito/carrito.component.ts, front-end/enbalde/src/app/pages/producto/producto.component.html, front-end/enbalde/src/app/pages/producto/producto.component.ts, front-end/enbalde/src/app/services/auth.guard.ts
Arreglado. También reparé el chequeo de rol que hacía que no se pueda entrar en el carrito.
=> 508 tk170 corregir calculo de total en carrito

front-end/enbalde/src/app/pages/carrito/carrito.component.html, front-end/enbalde/src/app/services/productos.service.ts, front-end/enbalde/src/app/shared/header/header.component.html, front-end/enbalde/src/assets/carrito.json, front-end/enbalde/src/assets/productos.json, front-end/enbalde/src/assets/ventas.json
Cambiar todos los titulo por nombre para que funcione el listado de ventas y la búsqueda
=> Fix ventas

back-end/django/enbalde/serializers.py, back-end/django/enbalde/urls.py, back-end/django/enbalde/views/carrito_views.py, back-end/django/enbalde/views/usuario_views.py, front-end/enbalde/src/app/services/auth.service.ts, front-end/enbalde/src/app/services/usuarios.service.ts
Primera parte del carrito, cada vez que un cliente se loguea se busca el carrito activo o se crea uno nuevo, si se loguea un admin no se crea ninguno. Esto permite que sin importar en qué navegador se conecte se comparta el carrito. Hasta que el carrito se venda va a seguir utilizandolo. Después veo cómo quitármelo cuando se vende.
=> 131 tk43 back de carrito de compras

back-end/django/enbalde/serializers.py, back-end/django/enbalde/urls.py, back-end/django/enbalde/views/carrito_views.py, front-end/enbalde/src/app/models/modelo.seleccion.ts, front-end/enbalde/src/app/pages/carrito/carrito.component.ts, front-end/enbalde/src/app/pages/catalogo/catalogo.component.ts, front-end/enbalde/src/app/pages/compras/compras.component.ts, front-end/enbalde/src/app/pages/producto/producto.component.ts, front-end/enbalde/src/app/pages/ventas/ventas.component.html, front-end/enbalde/src/app/services/carrito.service.ts
Tan pronto como se agrega un producto al carrito se descuenta del inventario porque es más simple. Todavía no hay forma de quitar productos del carrito.
=> 108 tk29 back para seleccionar producto a comprar

front-end/enbalde/src/app/pages/dashboard/dashboard.component.html, front-end/enbalde/src/app/pages/dashboard/dashboard.component.ts
Mensaje de éxito creado, y reset de campos.
=> [ADD]Mensaje de éxito realizado

back-end/django/enbalde/serializers.py, front-end/enbalde/src/app/pages/ventas/ventas.component.html, front-end/enbalde/src/app/pages/ventas/ventas.component.ts
=> 149 tk79 back de listado de ventas para administrador

back-end/django/enbalde/serializers.py, back-end/django/enbalde/urls.py, back-end/django/enbalde/views/compra_views.py, front-end/enbalde/src/app/models/modelo.compra.ts, front-end/enbalde/src/app/models/modelo.venta.ts, front-end/enbalde/src/app/pages/compras/compras.component.ts, front-end/enbalde/src/app/pages/ventas/ventas.component.html, front-end/enbalde/src/app/pages/ventas/ventas.component.ts, front-end/enbalde/src/app/services/compras.service.ts, front-end/enbalde/src/app/services/funciones.service.ts
=> Listado compras

front-end/enbalde/src/app/app-routing.module.ts, front-end/enbalde/src/app/shared/header/header.component.html
- Mover el logout a la derecha (pero antes del carrito en el caso del cliente).
- Quitar el contacto del admin, solo invitados y clientes pueden usar el formulario de contacto.
- El admin está bloqueado de la página de contacto
=> Acomodamiento encabezado

back-end/django/enbalde/models/__init__.py, back-end/django/enbalde/models/password_reset.py, back-end/django/enbalde/urls.py, back-end/django/server/settings.py, back-end/requirements.txt, front-end/enbalde/src/app/pages/restablecer/restablecer.component.html, front-end/enbalde/src/app/pages/restablecer/restablecer.component.ts, front-end/enbalde/src/app/services/usuarios.service.ts
Listo el reset de password. Se va a enviar un mail que tenga un token, con ese token se puede cambiar la clave. Los mensajes de error vienen de Django directamente, por eso están en inglés, y como te comunicás directamente con el servidor el chequeo de qué tan fuerte es el password lo hace allá.
=> 80 tk22 realizar back en python de pantalla de recuperación de contraseña

back-end/django/server/settings.py, front-end/enbalde/src/app/pages/registracion/registracion.component.ts
Cuando el usuario se registré cada campo volverá su valor por defecto a vacio.
=> Reestabelcer valores de formulario

front-end/enbalde/src/app/pages/catalogo/catalogo.component.html, front-end/enbalde/src/app/pages/catalogo/catalogo.component.ts
Al agregar desde el catálogo se descuenta una unidad, al llegar a cero se deshabilita el botón
=> Descontar del catalogo

front-end/enbalde/src/app/pages/carrito/carrito.component.ts, front-end/enbalde/src/app/pages/catalogo/catalogo.component.ts, front-end/enbalde/src/app/pages/contacto/contacto.component.ts, front-end/enbalde/src/app/pages/dashboard/dashboard.component.ts, front-end/enbalde/src/app/pages/login/login.component.ts, front-end/enbalde/src/app/pages/ofertas/ofertas.component.ts, front-end/enbalde/src/app/pages/perfil/perfil.component.ts, front-end/enbalde/src/app/pages/producto/producto.component.ts, front-end/enbalde/src/app/pages/registracion/registracion.component.ts, front-end/enbalde/src/app/pages/restablecer/restablecer.component.ts, front-end/enbalde/src/app/pages/resultado-api/resultado-api.component.ts, front-end/enbalde/src/app/pages/tipo-producto/tipo-producto.component.ts, front-end/enbalde/src/app/pages/usuarios/usuarios.component.ts
Debería andar el refresco del header
=> 635 tk213 ahora cuando te logueas no refresca la pagina

back-end/django/enbalde/admin.py, back-end/django/enbalde/urls.py, back-end/django/enbalde/views/__init__.py, back-end/django/enbalde/views/usuario_admin_view.py, front-end/enbalde/src/app/pages/item-usuario/item-usuario.component.css, front-end/enbalde/src/app/pages/item-usuario/item-usuario.component.html, front-end/enbalde/src/app/pages/item-usuario/item-usuario.component.ts, front-end/enbalde/src/app/pages/usuarios/usuarios.component.html, front-end/enbalde/src/app/pages/usuarios/usuarios.component.ts, front-end/enbalde/src/app/services/usuarios.service.ts
Ya es posible editar los usuarios, si no se pone clave no se va a sobreescribir, se puede cambiar el tipo de usuario.
=> Modificar usuarios

front-end/enbalde/src/app/pages/ofertas/ofertas.component.html, front-end/enbalde/src/app/pages/ofertas/ofertas.component.ts
Volver a aceptar ofertas sin artículos.
=> 650 tk217 ofertas sin articulos

front-end/enbalde/src/app/pages/compras/compras.component.css, front-end/enbalde/src/app/pages/compras/compras.component.html, front-end/enbalde/src/app/pages/dashboard/dashboard.component.html, front-end/enbalde/src/app/pages/envios/envios.component.html, front-end/enbalde/src/app/pages/item-envio/item-envio.component.css, front-end/enbalde/src/app/pages/item-envio/item-envio.component.html, front-end/enbalde/src/app/pages/item-envio/item-envio.component.ts, front-end/enbalde/src/app/pages/item-oferta/item-oferta.component.css, front-end/enbalde/src/app/pages/item-oferta/item-oferta.component.html, front-end/enbalde/src/app/pages/item-oferta/item-oferta.component.ts, front-end/enbalde/src/app/pages/item-producto/item-producto.component.css, front-end/enbalde/src/app/pages/item-producto/item-producto.component.html, front-end/enbalde/src/app/pages/item-producto/item-producto.component.ts, front-end/enbalde/src/app/pages/item-tipo-producto/item-tipo-producto.component.css, front-end/enbalde/src/app/pages/item-tipo-producto/item-tipo-producto.component.html, front-end/enbalde/src/app/pages/item-tipo-producto/item-tipo-producto.component.ts, front-end/enbalde/src/app/pages/item-usuario/item-usuario.component.css, front-end/enbalde/src/app/pages/item-usuario/item-usuario.component.html, front-end/enbalde/src/app/pages/item-usuario/item-usuario.component.ts, front-end/enbalde/src/app/pages/ofertas/ofertas.component.html, front-end/enbalde/src/app/pages/tipo-producto/tipo-producto.component.html, front-end/enbalde/src/app/pages/usuarios/usuarios.component.html, front-end/enbalde/src/styles.css
=> agregar cebra en listas
